spring:
  datasource:
    url: jdbc:mysql://localhost:3306/plex?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false
    username: root
    password: Momentalno11
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: validate
#  security:
#    user:
#      name: barilska
#      password: barilska